In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv("Naive-Bayes-Classification-Data.csv")

In [3]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [4]:
print(x)

[[40 85]
 [40 92]
 [45 63]
 ...
 [40 83]
 [40 60]
 [45 82]]


In [5]:
print(y)

[0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 1 1 0 1 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0 0 0 0 1 0
 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0
 0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0
 1 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0
 0 1 1 0 0 1 1 1 0 0 0 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1
 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1
 0 1 0 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1
 0 1 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1
 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 1
 0 0 1 1 1 0 0 0 1 1 1 0 

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=0)
print(x_train)

[[45 90]
 [45 73]
 [40 92]
 ...
 [40 83]
 [50 90]
 [50 75]]


In [7]:
print(y_train)

[0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0
 1 1 1 1 0 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 1
 1 0 0 1 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1
 0 1 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0
 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 1 1 1 1 0 1 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0
 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 0 1 1 0
 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0
 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0
 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 0
 0 0 0 1 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 1 1 0 0 1 0 0
 0 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1
 0 0 1 0 0 0 0 1 0 1 0 1 

In [8]:
print(y_test)

[1 1 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0
 1 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 1
 0 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0
 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1
 0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0
 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 1 1 0
 1 0 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 1 1 1 1 0 1 1 0 1 0]


In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [10]:
print(x_train)

[[ 0.08705845  1.11441825]
 [ 0.08705845 -0.71533994]
 [-0.66812298  1.32968392]
 ...
 [-0.66812298  0.36098841]
 [ 0.84223987  1.11441825]
 [ 0.84223987 -0.50007427]]


In [11]:
print(x_test)

[[ 1.59232439 -0.51466921]
 [-0.57034164 -0.51466921]
 [ 0.87143571 -1.05042437]
 [-0.57034164  0.44969007]
 [-0.57034164  0.77114316]
 [ 0.87143571  1.84265348]
 [ 0.87143571 -0.8361223 ]
 [-0.57034164 -1.1575754 ]
 [ 0.15054703  0.44969007]
 [ 0.15054703 -1.05042437]
 [ 0.15054703  1.84265348]
 [ 0.15054703  0.98544523]
 [-0.57034164 -0.8361223 ]
 [ 2.31321307 -1.58617952]
 [ 0.15054703 -1.1575754 ]
 [-0.57034164 -0.08606509]
 [ 0.15054703 -0.30036715]
 [ 0.15054703  1.52120038]
 [-0.57034164 -0.8361223 ]
 [-1.29123032  0.23538801]
 [-0.57034164  1.09259626]
 [-0.57034164  1.09259626]
 [-0.57034164  0.23538801]
 [-0.57034164  0.5568411 ]
 [ 0.87143571 -1.1575754 ]
 [-1.29123032 -1.1575754 ]
 [ 0.15054703 -0.51466921]
 [-0.57034164  0.23538801]
 [ 0.15054703  0.5568411 ]
 [ 0.15054703  0.77114316]
 [-1.29123032 -1.1575754 ]
 [ 0.87143571 -0.8361223 ]
 [ 0.87143571  1.30689832]
 [-0.57034164  1.52120038]
 [-0.57034164  0.5568411 ]
 [ 0.87143571 -0.08606509]
 [ 0.15054703  0.5568411 ]
 

In [12]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [13]:
y_pred = model.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[102   2]
 [ 26 119]]
