In [42]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [43]:
data = pd.read_csv("online_gaming_behavior_dataset.csv")
data.head()

PlayerID  Age  Gender Location GameGenre  PlayTimeHours  InGamePurchases  \
0      9000   43    Male    Other  Strategy      16.271119                0   
1      9001   29  Female      USA  Strategy       5.525961                0   
2      9002   22  Female      USA    Sports       8.223755                0   
3      9003   35    Male      USA    Action       5.265351                1   
4      9004   33    Male   Europe    Action      15.531945                0   

  GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
0         Medium                6                        108           79   
1         Medium                5                        144           11   
2           Easy               16                        142           35   
3           Easy                9                         85           57   
4         Medium                2                        131           95   

   AchievementsUnlocked EngagementLevel  
0                    25          Medium  
1                    10          Medium  
2                    41            High  
3                    47          Medium  
4                    37          Medium

In [44]:
data = pd.get_dummies(data, columns=['Gender','Location','GameGenre','GameDifficulty'])
data.head()

PlayerID  Age  PlayTimeHours  InGamePurchases  SessionsPerWeek  \
0      9000   43      16.271119                0                6   
1      9001   29       5.525961                0                5   
2      9002   22       8.223755                0               16   
3      9003   35       5.265351                1                9   
4      9004   33      15.531945                0                2   

   AvgSessionDurationMinutes  PlayerLevel  AchievementsUnlocked  \
0                        108           79                    25   
1                        144           11                    10   
2                        142           35                    41   
3                         85           57                    47   
4                        131           95                    37   

  EngagementLevel  Gender_Female  ...  Location_Other  Location_USA  \
0          Medium          False  ...            True         False   
1          Medium           True  ...           False          True   
2            High           True  ...           False          True   
3          Medium          False  ...           False          True   
4          Medium          False  ...           False         False   

   GameGenre_Action  GameGenre_RPG  GameGenre_Simulation  GameGenre_Sports  \
0             False          False                 False             False   
1             False          False                 False             False   
2             False          False                 False              True   
3              True          False                 False             False   
4              True          False                 False             False   

   GameGenre_Strategy  GameDifficulty_Easy  GameDifficulty_Hard  \
0                True                False                False   
1                True                False                False   
2               False                 True                False   
3               False                 True                False   
4               False                False                False   

   GameDifficulty_Medium  
0                   True  
1                   True  
2                  False  
3                  False  
4                   True  

[5 rows x 23 columns]

In [54]:

x = data.iloc[:, data.columns != "EngagementLevel"].values
y = data["EngagementLevel"].values
print(x)

[[9000 43 16.271118760553215 ... False False True]
 [9001 29 5.525961380570566 ... False False True]
 [9002 22 8.223755243499511 ... True False False]
 ...
 [49031 15 0.2400568811778107 ... True False False]
 [49032 34 14.017817977715389 ... False False True]
 [49033 19 10.083803582242297 ... True False False]]


In [55]:
print(y)

['Medium' 'Medium' 'High' ... 'High' 'Medium' 'Medium']


In [70]:
from sklearn.model_selection import train_test_split
train_x , test_x, train_y, test_y = train_test_split(x,y,test_size=0.25,random_state=0)

In [71]:
print(train_x)

[[29939 43 12.73119651865833 ... True False False]
 [17028 35 21.891368895354656 ... False True False]
 [39509 22 10.198932976672408 ... True False False]
 ...
 [39403 26 18.655736618402045 ... False True False]
 [30243 46 16.653393180265667 ... False False True]
 [11732 27 5.2881856935657465 ... False False True]]


In [72]:
len(train_x)

32027

In [73]:
len(x)

40034

In [74]:
from os import preadv
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)

In [75]:
print(train_x)

[[ 0.0788384   1.09827997  0.10580439 ...  1.00585597 -0.50222371
  -0.65698572]
 [-1.03947593  0.30038022  1.43132651 ... -0.99417812  1.99114456
  -0.65698572]
 [ 0.90776476 -0.99620688 -0.26062663 ...  1.00585597 -0.50222371
  -0.65698572]
 ...
 [ 0.89858334 -0.597257    0.96311456 ... -0.99417812  1.99114456
  -0.65698572]
 [ 0.10517002  1.39749238  0.67336559 ... -0.99417812 -0.50222371
   1.5221031 ]
 [-1.49820049 -0.49751953 -0.97123598 ... -0.99417812 -0.50222371
   1.5221031 ]]


In [76]:
test_x = scaler.fit_transform(test_x)


In [77]:
print(test_x)

[[-0.27312794 -0.39658987  1.37157386 ... -1.02312225  2.03533336
  -0.64549722]
 [ 0.12166224 -0.89115364 -1.55416204 ...  0.9774003  -0.49132001
  -0.64549722]
 [ 0.17552468 -1.08897915 -1.63246053 ... -1.02312225 -0.49132001
   1.54919334]
 ...
 [ 0.54644302 -0.49550262  1.36796605 ...  0.9774003  -0.49132001
  -0.64549722]
 [-0.57131043  0.98818869 -1.05331791 ...  0.9774003  -0.49132001
  -0.64549722]
 [-1.58719923 -0.99006639 -0.88923867 ... -1.02312225  2.03533336
  -0.64549722]]


In [78]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=7, metric="minkowski", p=2)
model.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=7)

In [79]:
y_pred = model.predict(test_x)

In [80]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y,y_pred)
print(cm)

[[1349   51  633]
 [  62  996 1033]
 [ 401  406 3076]]
